name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
        run: npm run build # <--- This runs the actual build command

      - name: Deploy to Vercel
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
