name: Build & Deploy

on:
  push:
    branches:
      - main # Change this if you're using a different default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint (optional)
        run: npm run lint

      - name: Build the app
        run: npm run build
      - name: Deploy to Vercel
      run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}

      # Optional: Test
      # - name: Run tests
      #   run: npm test

      # Optional: Upload artifacts if needed
